### ISSUE TITLE
运行demo_run.py报错，mac安装的dmg的appium

### ISSUE THREAD

**Issue by jaffson111** [ztwo/Auto_Analysis#1]
/usr/bin/python /Users/jaffson/develop/Auto_Analysis-master/demo_run.py
Traceback (most recent call last):
  File "/Users/jaffson/develop/Auto_Analysis-master/demo_run.py", line 37, in <module>
    public.CheckEnvironment.check_environment()
  File "/Users/jaffson/develop/Auto_Analysis-master/public/CheckEnvironment.py", line 13, in check_environment
    appium = U.cmd("appium -v").stdout.readlines()[0].strip()
IndexError: list index out of range

Process finished with exit code 1

**Comment by ztwo** [comment]
感谢反馈，检查appium是否存在的代码有些不严谨，已经在最新提交修复。
你需要在终端安装appium，demo_run.py会自动运行appium。appium安装方法在文档内有说明，
